delete folder hello world
NeoX-ASIA-Inc/QR-Codes-Scanner-demo pull request #3
Opened 2023-11-23 08:20 UTC by fry1999

2023-11-23 08:39 UTC, BlazingRockStorm reviewed
https://github.com/Varsharanee/flashcard_flutter_project

tham khảo project này, xoá folder linux, macos, windows, web

2023-11-23 08:40 UTC, BlazingRockStorm requested changes
https://github.com/Varsharanee/flashcard_flutter_project

tham khảo project này, xoá folder linux, macos, windows, web

2023-11-23 08:46 UTC, fry1999 commented
Oke a

2023-11-23 09:04 UTC, BlazingRockStorm commented
với phần code còn lại, phải chạy được ở trên mobile

2023-11-24 00:36 UTC, fry1999 commented
> với phần code còn lại, phải chạy được ở trên mobile.
> 
> Hint:
> 
> * developer mode của thiết bị, phần mềm và framework
> * chế độ debug
> * Viblo, Qiita, Stackoverflow, Google
> 
> Expect: có screenshot đã chạy sản phẩm ở mobile

![image](https://github.com/NeoX-ASIA-Inc/QR-Codes-Scanner-demo/assets/39319777/3e0500eb-7cdf-4135-8dfa-6d4e3bdd85ff)
E chạy được rồi nhá

2023-11-25 17:47 UTC, BlazingRockStorm approved these changes
![image](https://github.com/NeoX-ASIA-Inc/QR-Codes-Scanner-demo/assets/22587774/7fab8988-ae6a-4b65-97f8-bd308d2225be)

2023-11-25 17:47 UTC, BlazingRockStorm commented
Sorry anh review chậm. Em merge nhé

2023-11-26 04:19 UTC, merged