Have change name of project
NeoX-ASIA-Inc/QR-Codes-Scanner-demo pull request #5
Opened 2023-11-27 01:36 UTC by fry1999

2023-11-27 02:43 UTC, BlazingRockStorm requested changes
- Trả lời các câu hỏi được đặt ra trong pull request
- Dùng thư viện `font-awesome`, không dùng ảnh trực tiếp
- Trạng thái của 2 icon sẽ được lưu vào 1 file JSON. Tạo file JSON để lưu dữ liệu
- Hình như iOS chưa thấy code được compile?

2023-11-27 02:43 UTC, BlazingRockStorm commented on lib/main.dart
> -  runApp(const MyApp());
tại sao ở đây lại bỏ khai báo `const`?

2023-11-27 02:43 UTC, BlazingRockStorm commented on lib/main.dart
> +      home: HomePage(),
- giống comment trên
- Vai trò của param `title` ở trong code này?

2023-11-27 03:43 UTC, fry1999 commented
> * Trả lời các câu hỏi được đặt ra trong pull request
> * Dùng thư viện `font-awesome`, không dùng ảnh trực tiếp
> * Trạng thái của 2 icon sẽ được lưu vào 1 file JSON. Tạo file JSON để lưu dữ liệu
> * Hình như iOS chưa thấy code được compile?

Dạ ... đúng là đang gặp phải một bug. Giờ e chưa kịp fix lại, e giờ phải lên trường. Tối e fix lại nhé ^^

2023-11-28 06:48 UTC, BlazingRockStorm requested changes
Bỏ hết các chỗ Unused đi

2023-11-28 06:48 UTC, BlazingRockStorm commented on pubspec.yaml
> +     - assets/icons/
Unused

2023-11-28 06:48 UTC, BlazingRockStorm commented on lib/main.dart
> +import 'dart:io';
Unused

2023-11-28 06:48 UTC, BlazingRockStorm commented on lib/main.dart
> +import 'package:flutter_svg/flutter_svg.dart';
Unused

2023-11-28 06:48 UTC, BlazingRockStorm commented on lib/main.dart
> +import 'package:path_provider/path_provider.dart';
Unused

2023-11-28 11:42 UTC, fry1999 commented on lib/main.dart
> -  runApp(const MyApp());
Quá trình code lại e cũng không để ý nó. Lúc thử test chạy thì chương trình ko báo lỗi.

2023-11-28 11:42 UTC, fry1999 commented on lib/main.dart
> +      home: HomePage(),
Ban đầu nó dùng là biến tham số để truyền từ MyApp -> MyHomePage. Nhưng giờ e chỉnh sửa lại code thì ko cần biến đó nữa

2023-11-29 01:27 UTC, BlazingRockStorm requested changes

2023-11-29 01:27 UTC, BlazingRockStorm commented on assets/images/files/app_state.json
Xoá

2023-11-29 01:27 UTC, BlazingRockStorm commented on lib/main.dart
> +  runApp(MyApp());
```suggestion
  runApp(const MyApp());
```

2023-11-29 01:27 UTC, BlazingRockStorm commented on pubspec.yaml
> +     - assets/images/files/
```suggestion
     - json/
```
Lỗi naming convention

2023-11-29 01:27 UTC, BlazingRockStorm commented on lib/main.dart
> +        'https://www.youtube.com'; // Đổi URL này thành đường link YouTube
```suggestion
        'https://youtu.be/KRYQ12faxqw?si=tpsUhCv9oPIyjfKo';
```

2023-11-29 01:34 UTC, BlazingRockStorm commented on json/app_state.json
Chưa mô tả đúng cấu trúc dữ liệu thực tế. Anh cấp luôn file `.json`. Em dựa vào file JSON sửa code. 
```json
[
{
  "id": 1,
  "name": "Redmark",
  "scanned_status": "false"  
},
{
  "id": 2,
  "name": "Bluemark",
  "scanned_status": "false"
}
]
```

Em dựa vào JSON trên để sửa lại app nhé

2023-11-30 14:17 UTC, BlazingRockStorm approved these changes
![LGTM](https://image.lgtmoon.dev/229687)

2023-11-30 14:25 UTC, BlazingRockStorm commented
@fry1999 sau khi merge pull xong thì em làm nốt việc compile ra iOS nhé. Kết thúc thì em gửi `ipa` và `apk` qua Team cho anh

2023-11-30 15:23 UTC, merged